### ISSUE TITLE
[新增]:  您好可以私发我一下数据结构和计网的PPT吗，用于考研自学

### ISSUE THREAD

**Issue by AiDreamChaser** [WCY-dt/SEU-CyberSecurity-courses#4]
### 课程类型

None

### 需求描述

我的QQ 3149164241

### 提交前请确认

- [X] 我确认发布的内容不包含侮辱性、歧视性、攻击性内容。同时，我确保能够与他人友好地讨论问题。

**Comment by WCY-dt** [comment]
你好，已发送至QQ邮箱。

**Comment by WCY-dt** [comment]
你好，你的邮箱似乎无法正常发送邮件。
服务器返回码： smtp; 550 5.0.0 Mailbox unavailable or access denied

**Comment by AiDreamChaser** [comment]
你好，不好意思 ，我的邮箱出了点问题，现在已经修复好了，可以再麻烦同学发一下吗，谢谢
